#!/bin/bash

echo "🚀 MERN Task Tracker - Vercel Deployment Script"
echo "=============================================="

echo ""
echo "📋 Prerequisites Checklist:"
echo "1. MongoDB Atlas account (https://mongodb.com/atlas)"
echo "2. Vercel account (https://vercel.com)"
echo "3. Your project running locally ✅"
echo ""

echo "🗄️ Step 1: Set Up MongoDB Atlas"
echo "================================"
echo "1. Go to https://mongodb.com/atlas"
echo "2. Create free account"
echo "3. Create new project"
echo "4. Build database (FREE tier)"
echo "5. Configure database access (username/password)"
echo "6. Configure network access (Allow from anywhere)"
echo "7. Get connection string"
echo ""

echo "🚀 Step 2: Deploy Backend"
echo "========================"
echo "Run these commands:"
echo "cd /Users/abhaykumarverma/Documents/projects/fx-mern-task-tracker"
echo "vercel login"
echo "vercel"
echo ""

echo "🔧 Step 3: Set Backend Environment Variables"
echo "==========================================="
echo "After backend deployment, run:"
echo "vercel env add MONGODB_URI"
echo "# Enter your MongoDB Atlas connection string"
echo ""
echo "vercel env add JWT_SECRET"
echo "# Enter: your_super_secret_jwt_key_here_12345"
echo ""
echo "vercel env add NODE_ENV"
echo "# Enter: production"
echo ""

echo "🎨 Step 4: Deploy Frontend"
echo "========================="
echo "Run these commands:"
echo "cd client"
echo "npm run build"
echo "vercel"
echo ""

echo "🔧 Step 5: Set Frontend Environment Variables"
echo "============================================"
echo "After frontend deployment, run:"
echo "vercel env add REACT_APP_API_URL"
echo "# Enter: https://your-backend-domain.vercel.app"
echo ""

echo "🧪 Step 6: Test Deployment"
echo "========================="
echo "1. Open your frontend URL"
echo "2. Login with demo accounts:"
echo "   - Admin: admin@example.com / admin123"
echo "   - Employee: john@example.com / emp123"
echo "3. Test all features"
echo ""

echo "📖 For detailed instructions, see: VERCEL_DEPLOYMENT_STEPS.md"
echo ""
echo "🎉 Ready to deploy! Follow the steps above."

